### ISSUE TITLE
[FEATURE] Update_FeatureSection_For_Dark_Mode

### ISSUE THREAD

**Issue by asteriskayush007** [DEVRhylme-Foundation/new-website#57] opened 2024-12-10 17:43 UTC
### Feature title

#Update_FeatureSection_For_Dark_Mode

### Motivation

##Our CTO And Web Dev Lead Suggest me to Improve that bug

### Alternatives

Uploading Screen Recording 2024-12-10 at 9.53.45 PM.mov…

**Comment by Pal-prakash2** [comment] 2024-12-11 10:20
Can you assign this bug to me ? will look into this

**Comment by MAVRICK-1** [comment] 2024-12-11 10:25
@Pal-prakash2  is the issue is already solved by @asteriskayush007  , he will raise the PR by today

**Closed** 2024-12-17 11:19 UTC
Labels: enhancement
